/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { Input } from './input';

export interface AutosolveRequest {
  /** The question to solve. */
  question: string;
  /** Optional base64 encoded image. */
  image?: string;
  /** The inputs that have to be filled out. */
  inputs: Input[];
}
