/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Cat Fact API
 * An API for facts about cats
 * OpenAPI spec version: 1.0.0
 */

/**
 * Breed
 */
export interface Breed {
  /** Breed */
  breed?: string;
  /** Country */
  country?: string;
  /** Origin */
  origin?: string;
  /** Coat */
  coat?: string;
  /** Pattern */
  pattern?: string;
}
