/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { ChatMessage } from './chatMessage';

export interface Chat {
  id: string;
  user_id: string;
  messages: ChatMessage[];
  created_at: string;
}
