import type { ChatMessageAllOf } from './chatMessageAllOf';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { ChatMessageContent } from './chatMessageContent';

export type ChatMessage = ChatMessageContent & ChatMessageAllOf;
