/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { ChatMessageRole } from './chatMessageRole';

export type ChatMessageAllOf = {
  role: ChatMessageRole;
  created_at: string;
};
