/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type CreateSubscription200 = {
  /** The URL to redirect the user to, in order to complete the payment process.
   */
  redirect_url: string;
};
