/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type CreateChatParams = {
  /**
   * Id of notes tag that should be included in chat context.
   */
  noteTagId?: number;
};
