/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type CreateAutosolveChatBody = {
  /** Language in which the responses should be */
  language: string;
  /** Context of the problem */
  context: string;
};
