/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { LimitParameter } from './limitParameter';
import type { OffsetParameter } from './offsetParameter';

export type GetNotesParams = {
  /**
 * Maximum number of results to return. Defaults to 20.

 */
  limit?: LimitParameter;
  /**
 * Offset for pagination. Defaults to 0.

 */
  offset?: OffsetParameter;
  /**
   * Filter notes by tag id
   */
  tag_id?: number;
  /**
   * Filter notes by name
   */
  query?: string;
};
