/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Cat Fact API
 * An API for facts about cats
 * OpenAPI spec version: 1.0.0
 */

export type GetRandomFactParams = {
/**
 * maximum length of returned fact
 */
max_length?: number;
};
