/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Cat Fact API
 * An API for facts about cats
 * OpenAPI spec version: 1.0.0
 */

export * from './breed';
export * from './catFact';
export * from './getBreedsParams';
export * from './getFactsParams';
export * from './getRandomFactParams';