/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { TextInput } from './textInput';
import type { Select } from './select';

export type Input = TextInput | Select;
