/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

/**
 * Maximum number of results to return. Defaults to 20.

 */
export type LimitParameter = number;
