/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export interface NoteEdit {
  name: string;
  content: string;
  tag_id?: number;
}
