/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type PauseSubscriptionBody = {
  /** The date and time when the subscription will be resumed.
   */
  resumes_at: string;
};
