/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export interface Referral {
  referral_code: string;
  /** Number of users reffered by the current user.
   */
  nr_referrals: number;
}
