/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type SelectType = (typeof SelectType)[keyof typeof SelectType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SelectType = {
  select_single: 'select_single',
  select_multiple: 'select_multiple',
} as const;
