/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { SelectType } from './selectType';
import type { Choice } from './choice';

export interface Select {
  id: string;
  type: SelectType;
  label?: string;
  choices: Choice[];
}
