/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { SolutionValue } from './solutionValue';

export interface Solution {
  id: string;
  value: SolutionValue;
}
