/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionStatus } from './subscriptionStatus';

export interface Subscription {
  status: SubscriptionStatus;
  /** @nullable */
  price_id: string | null;
  current_period_start: string;
  current_period_end: string;
  cancel_at_period_end: boolean;
  is_payment_collection_paused: boolean;
  /** @nullable */
  payment_collection_paused_until: string | null;
  created_at: string;
  updated_at: string;
}
