/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { TagBase } from './tagBase';
import type { TagAllOf } from './tagAllOf';

export type Tag = TagBase & TagAllOf;
