/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type TextInputType = typeof TextInputType[keyof typeof TextInputType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextInputType = {
  input: 'input',
} as const;
