import type { TextInputFormat } from './textInputFormat';
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */
import type { TextInputType } from './textInputType';

export interface TextInput {
  id: string;
  type: TextInputType;
  label?: string;
  format: TextInputFormat;
}
