/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * ClassMate backend
 * ClasssMate backend
 * OpenAPI spec version: 1.0
 */

export type TextInputFormat = typeof TextInputFormat[keyof typeof TextInputFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextInputFormat = {
  text: 'text',
  number: 'number',
} as const;
