name: i18n
on:
  # Only run on PRs into master
  pull_request:
    branches:
      - master

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Check Localization
        run: |
          pnpm i18n
